language: node_js
node_js:
- '5.5'
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
  - "$HOME/.gem"
before_install:
- npm install -g gulp
script:
- gulp test
- gulp
deploy:
  provider: npm
  email: npm@airbug.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: DLGYrPQtq8cKw3mU+GqOfcbboPd8yqEixQVOsBr23hHHqTgYrOdbDQVXUUrYfYYMtNO89l6DXh6YIyLsbqJsry5DLCKyr6H20CIIhqwdUduPK88u1J3G375IBZJum4r1nc3wc7R9emiuFxLfJUNdSnUE2mxT6PVuiYsxY1u4P3renzCxrZ0lkvg8Kel+bJT8ri82KsH9ncz4lpEcYg+3ltgoxhwD42x2HXus+iZdrRVNhqFwPDq+QdYux/iFZ4blGcbuXwUx1jyxTYf5Pz2M1uQqXgCMvFt9Uv+4ZCc4ogFBgbXUekAh+dUnF5gqOBYuUzLpnJ86K1kKc3O37GGQKAECXBqsGUV/JasfTfftUo5lZXaukomVdQkgfFgwbcaH7MomYEcyHB3G5tNczOFJKWOaJoNpkozQBR8/nCoKWBIPiOb2w2ZXWcKj/HR36fOb27mD5ja094fkWgw1NA6SmjkXb6G4YzCeDhWMNogD8br6Kgk+wQQmFltP42vkpSQfXo3x7FKT3Enhmdhk0WJaj7KoVtyr+ohtYaSKZL1euR8AYmtTMmhcsK8bNcEf0W9MNQqgNd/Msq3m9rK04BeaiNAb+1jqgoMuWjzmeJ2jV1vVChhMjXOE4SRUEp02g9ojnUJrwshXM+zu7nc4rfZb6zk/RqgfTt1JHdAsb5u6pXU=
