language: node_js
node_js:
  - '5.3'

cache:
  directories:
    - node_modules
    - $HOME/.npm
    - $HOME/.gem

before_install:
  - npm install -g gulp

script:
  - gulp test

before_deploy:
  - gulp

deploy:
  provider: npm
  email: npm@airbug.com
  skip_cleanup: true
  api_key:
    secure: A41KuqZ1UhBGWs8ANakQXegawZ00OZg5tM357mJM7hQFRqepXh6ujpPIeuPZaHbiPnFMucQ5rgjyjW+dOtAn0iog+L/bocMliDv+2mdCr8MfQdcXpiF0vvAq9u38UIRrFnb+C7T/QieFfCz9r1wnunyY9heL+1Q1k97XPsChl9wtGsj2M6AlMuhteL3q1THJZj3k4ETjnTyXfzkSDhEP4vWtzHSXq28AjAN3e7vZKokmDGm8l4TbucKOxANTW0WaT4CR2yU65SyRCPwS277btgtuxw+wgTNye3M/+Oo4xFY5SZi98jUZz2gcecZrjX5HHOATTRBxreKn1RW/eB8kyLnHS0itXAtVLsFs4z5H3sSlslV6dujRb12gJh9KvRkKWn+7tIZE4VQA1Hj/4ILDZZ0GbMSJtjlbmUb0w3Z7DYHDucbxJonfd4sM24HkOxJl6ygbkI1PWGtHy/B0TVFABbMuyK2dQYZCQOfP4QCI+hJixTtdYaBVZ8jwL7GrOY4sKgwiDIqRcor+48b3x0F4U5mDs9y/1rt+s/ydkwgqKSPuSImHD33yUqnScZQm6pEwQhOagqTF4iHlwO2zMsZTM5n3txPh5mxtfXKXMKGrq3/sslAIwmrickb7EONRrlnzOVtPyBlV8IZFYmXO1NOF0OgrX4sm6LG9z6kFhyeQEpk=
  on:
    tags: true
